### ISSUE TITLE
Hide map that now shows in 4.3

### ISSUE THREAD

**Issue by Daxito** [dji-sdk/Mobile-UILibrary-iOS#12]
Hi,
I just updated the library from 4.2 to 4.3 and there is a map in one corner of the screen that I am not sure how to hide, are there any docs about how to hide this?

Thanks

**Comment by nhantrivinh** [comment]
Also repositioning after the views after removing a widget would help too!

**Comment by fontained** [comment]
Hi @Daxito, I had the same request and I did it like this. In you main controller,
`        if (self.previewViewController is DULMapViewController){
            self.previewViewController?.view.isHidden = true
        }
`
Hope this will help you. 
Best regards

**Comment by Daxito** [comment]
@fontained it worked!! Thanks!!
