### ISSUE TITLE
Black Screen using iOS 11 and iPhone 6-7

### ISSUE THREAD

**Issue by Daxito** [dji-sdk/Mobile-UILibrary-iOS#14]
Hi,

After updating our iPhones (iPhone 6 and 7 so far) to iOS 11, and using the SDK version 4.3 and 4.3.1, when we connect the drone to the phone, we get a black image for around 40 seconds or a minute before we can actually see what the drone is seeing.
Please let me know if you need more info.

Thanks

**Comment by athiercelin** [comment]
Thanks for reporting this, we already are investigating a bunch of video problem with iOS11

**Comment by XietongLU** [comment]
@Daxito we cannot reproduce the issue. Maybe you can provide us more information: 
1. Please check if the video previewer you are using is the latest version. We updated it in the beginning of September. 
2. Please check if there is video feed came from the DJIVideoFeed delegate. 
3. If you have more detailed steps, please let us know.

**Comment by Daxito** [comment]
Updating the Video Previewer fixed my issue, thank you!
