### ISSUE TITLE
Add Widget to DULStatusBarViewController make icon bigger than others.

### ISSUE THREAD

**Issue by guicolares** [dji-sdk/Mobile-UILibrary-iOS#22]
I would like add some other Widgets on StatusBarViewController from UILibrary but that is bigger than others even change the frame. 

Here is my code below to add the widget: 
"ViewWillAppear":
`self.statusBarVC.addWidget(DULRemoteControlSignalWidget(frame: CGRect(x: 0, y: 0, width: 63, height: 25)))`
`self.statusBarVC.statusBarView?.reloadData()`

I am using:
DJI-SDK-iOS,  4.3
DJI-UILibrary-iOS, 4.3
Xcode 9 
Device tested 10 and 11

There is a image to make easier understand my problem below.
![img_0167](https://user-images.githubusercontent.com/6391551/32223398-4e86eb78-be24-11e7-8293-fef1edda8130.PNG)

Thanks to made this Library for us.

**Comment by aksh1t** [comment]
Instead of just doing `addWidget`, use the other method with `addWidget:withEdgeInsets` and set the insets to be 10 for bottom and top. It should adjust similar to the other widgets then.

**Comment by guicolares** [comment]
It worked!!!

Thanks, you are the guy.
