### ISSUE TITLE
DULExposureSettingsController crash with DJI SDK 4.1

### ISSUE THREAD

**Issue by dbaldwin** [dji-sdk/Mobile-UILibrary-iOS#4]
Am curious if the current UI library (4.0.1.1.0.0) is compatible with SDK 4.1. Most of the widgets work but when using the DULExposureSettingsController we get the following error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[DJICameraCapabilities sharedInstance]: unrecognized selector sent to class 0x107bd2578'

To verify this all I did was update the UI Lib swift project podfile to this:

#platform :ios, '9.0'

target 'UILib Sample' do
  pod 'DJI-SDK-iOS', '~ > 4.1'
  pod 'DJI-UILibrary-iOS', '~ > 4.0.1.1.0.0'
end

Whenever trying to access the "Panels and Collections" view it immediately crashes with the error above. 

Do we need to wait for an update to the UI library or is there a workaround in the interim?

Thank you.

**Comment by zoemcateedji** [comment]
We will be releasing an update to the UI Library soon, and this compatibility issue is one of the things it addresses.

**Comment by dbaldwin** [comment]
Thank you @zoemcateedji !
