### ISSUE TITLE
Cannot find and use the DULVisionChecklistItem

### ISSUE THREAD

**Issue by Sunnyyoung** [dji-sdk/Mobile-UILibrary-iOS#9]
## Description

Cannot find any `DULVisionChecklistItem` header file. But it is mentioned in official documents: http://developer.dji.com/api-reference/ios-uilib-api/Widgets/DULVisiionChecklistItem.html

## Environment

SDK Version: 4.2

**Comment by Sunnyyoung** [comment]
- [DULRemoteControllerBatteryChecklistItem](http://developer.dji.com/api-reference/ios-uilib-api/Widgets/DULRemoteControllerBatteryChecklistItem.html)
- [DULAircraftBatteryTemperatureChecklistItem](http://developer.dji.com/api-reference/ios-uilib-api/Widgets/DULAircraftBatteryTemperatureChecklistItem.html)

Has the same issue, can not find the header files.

**Comment by fontained** [comment]
Could you please provide the header files? I have the same issue.

**Comment by oliverou** [comment]
Hi @Sunnyyoung @fontained , we have just published the iOS UILibrary 4.3, the issue is resolved, please check it. Thanks!
